<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ftec.projetoweb.TrabalhoCarrinho.Dominio\ftec.projetoweb.TrabalhoCarrinho.Dominio.csproj" />
    <ProjectReference Include="..\ftec.projetoweb.TrabalhoCarrinho.Persistencia\ftec.projetoweb.TrabalhoCarrinho.Persistencia.csproj" />
  </ItemGroup>

</Project>
